### PR TITLE
Adding russian translations and updating SDK Build Tools version

### PR DESCRIPTION
**Pull request by proninyaroslav**

### CODE REVIEW

**Comment by wslany** [comment]
Dear @proninyaroslav please update translations only via http://translate.catrobat.org/ --- the entries on github will be overwritten regularily by those from http://translate.catrobat.org/ --- thanks!

**Comment by proninyaroslav** [comment]
@wslany
Ok. How to be with updating Build Tools version?

**Comment by wslany** [comment]
@proninyaroslav Re updating Build Tools version: sorry I am the wrong person for that. @X4mp could you please answer that?

**Comment by AlxO** [comment]
@proninyaroslav We will update the Build Tools Version soon with the new release.

**Pull request closed without merging**
