### PR TITLE
PAINTROID-392 Layer redesign

### PR DESCRIPTION
**Pull request by Lenkomotive**
Redesigned the layerview according to mockup.

[PAINTROID-392](https://jira.catrob.at/browse/PAINTROID-392)

image

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by SebastianGrief — APPROVED** [review]
LGTM 👍

**Review by exland — APPROVED** [review]
Good commit

**Comment by ThorstenBandel** [comment]
One small change request: please add the newline at the end of the new xml file, after that i will merge it

**Comment by ThorstenBandel** [comment]
There is a small bug:

1. Create 3 Layers
2. Set transparency of last layer < 100%
3. Delete last layer
4. Undo
5. Open Layer menu
6. Last layer is missing (But only in the view, if you actually just draw and then reopen the layer menu, then it reappears
)

**Pull request merged**
