### PR TITLE
PAINTROID-506 Fixed SaveCompressImageIntegrationTests

### PR DESCRIPTION
**Pull request by Rd4dev**
PAINTROID-506
SaveCompressImageIntegrationTest failed as testSaveImage() didn't receive appropriate compressed bitmap

Fix:
- load_image action was performed which was uneccesary for this test.
- DecodeBitmapFromUri failed to provide compressed bitmap so replaced it with getScaledBitmapFromUri() to  return a downscaled bitmap that can be loaded efficiently into the memory
- Matchers.equalTo() only accepts bitmap of 1280 X 720 but compressed bitmap could be anywhere below them so changed it to Matchers.lessThanOrEqualTo()

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aayush2111** [comment]
hey!
please fix the failing test: jacocoTestDebugUnitTestReport, as it can be seen here: https://jenkins.catrob.at/job/Paintroid/job/PR-1215/
I guess it will be fixed by updating jacoco {
    toolVersion = "0.8.5" //FROM
    toolVersion = "0.8.7" //TO
}
:)

**Comment by Rd4dev** [comment]
Thanks, @Aayush2111 for helping out!
Fixed the Unit Tests :)

**Review by khalid-nasralla — APPROVED** [review]
PR looks good to me.

**Review by ThorstenBandel — APPROVED** [review]

**Comment by Rd4dev** [comment]
Thanks @ThorstenBandel @khalid-nasralla

**Pull request merged**
