### PR TITLE
PAINTROID-95: app name in ActionBar

### PR DESCRIPTION
**Pull request by SebastianGrief**

### CODE REVIEW

**Comment by mrmattmueller** [comment]
Text has the wrong color (black), please also talk about the alignment with Vesna. Thx!

**Comment by ThomasSchwengler** [comment]
Text color depends on #682 where the actionbar theme is set to a consistent style

**Comment by geolas94** [comment]
rebuilding on jenkins passes all tests

**Comment by ThomasSchwengler** [comment]
Please rebase

**Comment by wslany** [comment]
Thanks --- hoping for the best...

**Pull request merged**
