### PR TITLE
PAINTROID-447: refactored test cases

### PR DESCRIPTION
**Pull request by akebu6**
Jira Ticket: https://jira.catrob.at/browse/PAINTROID-447

Refactored 4 test files from Java to Kotlin:
- LandscapeIntegrationTest
- MainActivityIntegrationTest
- SaveCompressImageIntegrationTest
- UndoRedoIntegrationTest

Also worked on `CatrobatImageIOIntegrationTest .kt` to fix initialisation error of `uriFile`

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by AneiMakovec — CHANGES_REQUESTED** [review]
Some refactored tests crash on Jenkins and locally. Reasons for errors in each file:

- LandscapeIntegrationTest.kt - kotlin.UninitializedPropertyAccessException: lateinit property currentTool has not been initialized
- MainActivityIntegrationTest - initializationError: I think the problem is with the rules.

Please fix the above refactored tests, so that they run.

**Comment by akebu6** [comment]
> Some refactored tests crash on Jenkins and locally. Reasons for errors in each file:
> 
> * LandscapeIntegrationTest.kt - kotlin.UninitializedPropertyAccessException: lateinit property currentTool has not been initialized
> * MainActivityIntegrationTest - initializationError: I think the problem is with the rules.
> 
> Please fix the above refactored tests, so that they run.

All right, I shall work on them

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by akebu6** [comment]
@AneiMakovec I have worked on the requested changes, however, I have noticed that there is a file which uses a lateint variable that is never initialised and it's not one of the tests that I was working on. Should I work on it as well? because it will keep making the tests fail

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by AneiMakovec** [comment]
Could you please write the name of that file?

**Comment by akebu6** [comment]
CatrobatImageIOIntegrationTest .kt, just right after the BitmapIntegrationTest.

'uriFile' is declared as a lateinit and not initialised after

**Comment by AneiMakovec** [comment]
I see, it does crash the test. The file is not in the scope of this ticket, but I did not see any ticket about it on Jira. So it's up to you if you decide to fix it or not. If you do, make sure to mention it in this pull request's description.

**Comment by AneiMakovec** [comment]
Also I took a look at the changes and the test run, which is nice. But there are some tests in both the LandscapeIntegrationTest.kt and MainActivityIntegrationTest.kt files that fail. Please make sure that they all pass, as they did before the refactoring.

**Comment by akebu6** [comment]
I'll look into those as well

**Comment by akebu6** [comment]
> I see, it does crash the test. The file is not in the scope of this ticket, but I did not see any ticket about it on Jira. So it's up to you if you decide to fix it or not. If you do, make sure to mention it in this pull request's description.

I can work on it later today then

**Review by AneiMakovec — APPROVED** [review]
Refactored tests run and work locally and on Jenkins.

**Review by ThorstenBandel — APPROVED** [review]
LGTM

**Pull request merged**
