### PR TITLE
PAINTROID-163: Save temporary copies automatically

### PR DESCRIPTION
**Pull request by JulianJautz**
when the application is closed unexpectedly drawing should not be lost

* painting is saved after 2 sec without user interaction and after 60 sec regardless interaction --> using coroutine
* creating new image deletes temporary files
* when application is started saved painting is loaded automatically (always, creating new image can delete saved state)

https://jira.catrob.at/browse/PAINTROID-163

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Electronix1337 — CHANGES_REQUESTED** [review]
Implementation itself looks fine and works properly, but a lot of tests fail locally and process constantly crashes after certain amount of tests (~50 with my local machine). Maybe disable the auto-saving while testing and explicitly enable it for your auto-save test suite? Got a lot of failing tests due to the fact that if emulator is "stuck"/idle for 2 seconds which happens quite regularly, a auto-save happens and when next test is being run, the auto-saved image will be loaded, which messes up a lot of tests (Layertests all failed for me locally and process eventually crashed -> test suite did not run further). Another option would also be to increase time for auto-saving to maybe 10 seconds which should also suffice as 10 seconds of lost progress is not that severe.

**Comment by JulianJautz** [comment]
Sorry, totally forgot to check the tests again after I fixed all UnitTests. Didn't consider that I won't get Espresso results when UnitTests fail...
I think the better option is to exclude auto save while testing. Which I found a solution for, but not for again including auto save in the new auto save tests. Do you know how to do that by chance?

**Comment by Electronix1337** [comment]
> Sorry, totally forgot to check the tests again after I fixed all UnitTests. Didn't consider that I won't get Espresso results when UnitTests fail... I think the better option is to exclude auto save while testing. Which I found a solution for, but not for again including auto save in the new auto save tests. Do you know how to do that by chance?

My first guess would be to just use a boolean which is true in normal app mode and in your auto-save-suite and false otherwise or something like that. Though there might be prettier solution out there for this problem.

**Comment by JulianJautz** [comment]
> My first guess would be to just use a boolean which is true in normal app mode and in your auto-save-suite and false otherwise or something like that. Though there might be prettier solution out there for this problem.

I pushed a solution with intents some days ago, please have a look again.

**Review by Electronix1337 — APPROVED** [review]
LGTM

**Review by wslany — CHANGES_REQUESTED** [review]
I think my commit broke something, the PR cannot be built anymore. Also there is a new smudge tool and also the "Set center" button in the Transform tool, so that might require changes.  Has the .catrobat-image format version been correctly increased for the new features? There should be some version number to check for up- and downwards compatibility, no?

Please, when you change stuff anyway, also increase the copyleft date in the headers of the files that are edited by the PR where it has not yet been done, for instance in https://github.com/Catrobat/Paintroid/blob/2e5344b54dadc0237342d88afc6c284ba16bed57/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/MainActivityIntegrationTest.java#L3

**Review by wslany — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Please resolve the lint warning https://jenkins.catrob.at/job/Paintroid/job/PR-1074/18/analysis/origin.-1038071647/source.23291eb0-0493-4601-aea1-9b193eeceeef/#19 

Please also squash to a single commit.

**Comment by JulianJautz** [comment]
I sqashed the commits and resolved the warning, but this warning was not generated by my changes and also affects other PRs.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
> I sqashed the commits and resolved the warning, but this warning was not generated by my changes and also affects other PRs.

Thanks!

**Pull request merged**
