### PR TITLE
PAINTROID-212: Adapt format to original image

### PR DESCRIPTION
**Pull request by wslany**
https://jira.catrob.at/browse/PAINTROID-212

first changed the format option for the loaded image
second changed the format option for the new image

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by wslany** [comment]
@CodeChamp-SS sorry I made a mistake with #879 --- please, 🙏 can you rebase and squash your commits into one?

**Comment by CodeChamp-SS** [comment]
> @CodeChamp-SS sorry I made a mistake with #879 --- please, 🙏 can you rebase and squash your commits into one?

ah.. didn't get it😅, you want @harsh-hash to squash the commits? As I didn't create that pr😅

**Comment by wslany** [comment]
> > @CodeChamp-SS sorry I made a mistake with #879 --- please, 🙏 can you rebase and squash your commits into one?
> 
> ah.. didn't get it😅, you want @harsh-hash to squash the commits? As I didn't create that pr😅

Correct, sorry! Too many open PRs... 😅

**Comment by harsh-hash** [comment]
@wslany sir I made the mistake of pulling and pushing it so can you tell me what to do ? or should I make a new PR?

**Comment by wslany** [comment]
> @wslany sir I made the mistake of pulling and pushing it so can you tell me what to do ? or should I make a new PR?

You can make a new one no problem, or you can force push to this one, either way. If you make a new one, please close this one.

**Comment by harsh-hash** [comment]
@wslany sir, closing this PR.  [=> 888](https://github.com/Catrobat/Paintroid/pull/888)

**Pull request closed without merging**
