### PR TITLE
PAINTROID-156 spray can tool

### PR DESCRIPTION
**Pull request by StanglTobias**
- Ignored tests that fail because PAINTROID-126 did not adapt tests. Tests should be fixed in a separate ticket
- Added spray can tool with changeable radius.
- Removed Pipette tool from tool selection
- Failing tests pass on local device 

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by FromG — APPROVED** [review]
lgtm.

**Review by wslany — CHANGES_REQUESTED** [review]
Very nice!

Four changes please:

1) The size of the spray area is too large, which makes it difficult to use it meaningfully in practice, see screenshot below (for an image of size 720 × 1480). The size numbers are written next to the spray area, and also a line drawn with the brush of the same width next to it. Please make it so that the width is **three times** the width of the corresponding brush size. Currently it seems more like a factor of 10 times for the 50 size, but even more for the 1 size.
Screenshot_20210109-092350

2) Make the starting value the same as for the brush, i.e., it shouldn't be 1 but 6 as the default value. Afterwards, it shall not have to be coordinated with the width of the brush, i.e., no change for that. This is just about the initial value. 
 
3) Make it spray, i.e., appear, a bit more slowly, so that the density appears more slowly, so one has more time to control it, _especially_ when drawing lines, which is a typical case. I would say, around 3 times more slowly. See the following screenshot on how fast it appears now, when one draws a line with the same, normal speed that allows to control where the line goes. Note that this is also linked with number 1 above and number 4 below. It should be coordinated and balanced with them, to make it easy to draw precisely, in a controlled way.
Screenshot_20210109-100334

4) Make it appear the slower the smaller the size, so that it looks approximately of the same density for the same duration, independently of the size. Here an image how it currently looks like, on the left, when I touched as shortly as possible, and on the right, when I touched a bit longer, approximately for the same amount of time for each size. The density should be roughly the same, but it isn't:
Screenshot_20210109-092459

**Comment by wslany** [comment]
One more thing regarding the speed of spraying: it should be the same on future devices, i.e., not become faster the faster the hardware becomes.

**Review by FromG — APPROVED** [review]
lgtm

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
