### PR TITLE
Paintroid-471:Refactor test cases from Java to Kotlin

### PR DESCRIPTION
**Pull request by juliajulie95**
Fixed conflicts for https://github.com/Catrobat/Paintroid/pull/1204

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by juliajulie95** [comment]
please use merge & squash feature to merge

**Comment by ThorstenBandel** [comment]
Please fix the static warnings in https://jenkins.catrob.at/job/Paintroid/job/PR-1208/1/analysis/

**Comment by bakicelebi** [comment]
> Please fix the static warnings in https://jenkins.catrob.at/job/Paintroid/job/PR-1208/1/analysis/

Fixed :+1:

**Review by exland — APPROVED** [review]

**Review by Lenkomotive — APPROVED** [review]

**Review by ThorstenBandel — APPROVED** [review]
LGTM

**Pull request merged**
