### PR TITLE
PAINTROID-486 Keyboad does not hide after leaving RGB-View

### PR DESCRIPTION
**Pull request by Smarshal21**
*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

untitled

Fixed Keyboad does not hide after leaving RGB-View

### CODE REVIEW

**Comment by Smarshal21** [comment]
@mfuchs @dldnhf @meisterluk @clempe  can you please review this PR and let me know the changes

**Comment by meisterluk** [comment]
I still don't know why you always tag me. I am not involved in Catrobat projects anymore since 2015. So please proceed without me. I will ignore any future requests by Catrobat.

**Comment by Smarshal21** [comment]
@exland  can you please review this PR

**Comment by Lenkomotive** [comment]
Hey @Smarshal21! 
The fix itself looks good. 
Have you ran the tests, especially espresso, locally? In Jenkins 69 of them failed (Usually ~15 fail). Please verify whether your fix had an influence on this. And please write a test in  `ColorDialogIntegrationTest.java` to verify your solution. 

Cheers

**Review by Lenkomotive — COMMENTED** [review]
Looks good

**Review by Lenkomotive — APPROVED** [review]

**Review by exland — APPROVED** [review]
Good fix

**Comment by Smarshal21** [comment]
@exland can i get this pr merged ?

**Review by juliajulie95 — APPROVED** [review]
Thank you!

**Pull request merged**
