### PR TITLE
PAINTROID-223: Large images that are scaled down are upside-down (tur…

### PR DESCRIPTION
**Pull request by lnx2000**
Ticket Solve: [https://jira.catrob.at/browse/PAINTROID-223](https://jira.catrob.at/browse/PAINTROID-223)  

* Used ExifInterface to get orientation flag and rotated bitmap accordingly
* Created test for the same

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks, works very nicely! 

Please fix the lint warnings: https://jenkins.catrob.at/job/Paintroid/job/PR-859/1/analysis/

Comparison:
image

**Comment by wslany** [comment]
https://jenkins.catrob.at/job/Paintroid/job/PR-859/2/analysis/

**Comment by lnx2000** [comment]
@wslany sir, 
There's one warning regarding [ExifInterface](https://jenkins.catrob.at/job/Paintroid/job/PR-859/3/analysis/origin.-1038071647/moduleName.644888918/source.a398384a-838f-439c-990e-4844b3a810e0/#33). To get rid of this I need to add `androidx.exifinterface:exifinterface:1.3.2` dependency.
Should I do that?

**Comment by wslany** [comment]
> @wslany sir,
> There's one warning regarding [ExifInterface](https://jenkins.catrob.at/job/Paintroid/job/PR-859/3/analysis/origin.-1038071647/moduleName.644888918/source.a398384a-838f-439c-990e-4844b3a810e0/#33). To get rid of this I need to add `androidx.exifinterface:exifinterface:1.3.2` dependency.
> Should I do that?

Yes please.

**Review by wslany — COMMENTED** [review]
I am not sure why but lint still reports an issue:

image

image

Please try to get rid of that warning. I will also ask in the team that you get a code reviewer. I am the product owner, so will do the final review. I looks fine to me.

**Comment by lnx2000** [comment]
Actually the same import order was there in main develop branch that's why 
I didn't looked much into it.

**Review by ldirry — CHANGES_REQUESTED** [review]
Hi, code looks nice to me.
However, please fix the lint warning by moving the `androidx` imports below the `java.util` imports.
I would also like to see at least one testcase for the method `getBitmapOrientation(..)` when the `ExifInterface` returns a certain Orientation.

**Comment by lnx2000** [comment]
@ldirry All the warnings gave gone now. Thank you very much.
Please review it once

**Review by ldirry — APPROVED** [review]

**Comment by ldirry** [comment]
looks good to me now :)

**Review by wslany — APPROVED** [review]

**Pull request closed without merging**
