### PR TITLE
PAINT-285 Text Tool Options

### PR DESCRIPTION
**Pull request by ndrnour**
* The Text tool options should be switched around,
 * with font and style options (and removed font size option, as sizing should be done on screen)

### CODE REVIEW

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
screenshot_20180320-101812

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ThomasSchwengler** [comment]
LGTM :+1: 

Sorry for the delay :/

**Pull request merged**
