### PR TITLE
PAINTROID-446: refactored test files

### PR DESCRIPTION
**Pull request by akebu6**
Refactor the following files from java/org/catrobat/paintroid/test/espresso:

- BitmapIntegrationTest
- FileFromOtherSourceIntegrationTest
- ToolOptionsIntegrationTest
- ToolSelectionIntegrationTest
- StatusbarIntegrationTest
- Ticket: https://jira.catrob.at/browse/PAINTROID-446

Also worked on `CatrobatImageIOIntegrationTest .kt` to fix initialisation error of `uriFile`  and removed the waitForToast() in `ToolSelectionIntegrationTest`, because the file was causing all tests to fail in both the original Java file and refactored Kotlin file

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

### CODE REVIEW

**Review by AneiMakovec — CHANGES_REQUESTED** [review]
All refactored tests fail on Jenkins and locally because of an initializationError. I suspect that the reason may be an inappropriate @Rule annotation. Please fix the refactored tests, so that they run. As an example for rules, you can look into the OraFileFormatIntegrationTest.kt file.

**Comment by akebu6** [comment]
I think I saw that but since it built it run locally on my machine I might have neglected it. Will fix that. Thanks

**Comment by AneiMakovec** [comment]
A few tests still crash because of an initializationError:

- FileFromOtherSourceIntegrationTest
- ToolOptionsIntegrationTest
- ToolSelectionIntegrationTest

**Comment by akebu6** [comment]
These tests weren't part of the ones being refactored in the ticket and I'm not sure how they got affected but I'll look into it

**Comment by akebu6** [comment]
However, the tickets were refactored in later tickets. But I'll be sure to see how best I can fix them and if not then I'll ask for help

**Comment by akebu6** [comment]
All tests pass locally for all 6 files: BitmapIntegrationTest, FileFromOtherSourceIntegrationTest, ToolOptionsIntegrationTest,, ToolSelectionIntegrationTest, StatusbarIntegrationTest as well as CatrobatImageIOIntegrationTest, run them five times to be sure. So, if they fail then I don't know what could be the main reason for the failure

**Review by AneiMakovec — APPROVED** [review]
All refactored tests run and work both locally and on Jenkins.

**Review by ThorstenBandel — APPROVED** [review]
LGTM!

**Pull request merged**
