### PR TITLE
PAINTROID-211 : Reverse order of jpg and png in save / copy / export settings

### PR DESCRIPTION
**Pull request by riturajjain2000**
Fixes [Paintroid-211](https://jira.catrob.at/projects/PAINTROID/issues/PAINTROID-211?filter=allopenissues)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by riturajjain2000** [comment]
Facing error `java.lang.Exception: Test class should have exactly one public zero-argument constructor` , plz help. I am new to espresso testing

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks! But, these tests have no connection to the ticket, no? Please only write meaningful tests.

Also, please rewrite the tests to Kotlin. 

In case there are still lint issues, please make sure to fix them before you make the PR, see https://jenkins.catrob.at/job/Paintroid/job/PR-845/1/analysis/ for the current ones (but they will change once you write the correct tests).

The tests must *fail* first (we use test-driven-development). Once there are meaningful tests, make a PR and let me know.

**Comment by riturajjain2000** [comment]
> Thanks! But, these tests have no connection to the ticket, no? Please only write meaningful tests.
> 
> Also, please rewrite the tests to Kotlin.
> 
> In case there are still lint issues, please make sure to fix them before you make the PR, see https://jenkins.catrob.at/job/Paintroid/job/PR-845/1/analysis/ for the current ones (but they will change once you write the correct tests).
> 
> The tests must _fail_ first (we use test-driven-development). Once there are meaningful tests, make a PR and let me know.

OK sir , I'll try to implement this , but I'll need some time to learn it as I am new to testing , if you want you can assign the issue to someone else in the meantime !

**Comment by wslany** [comment]
OK then, thanks and let's close the PR until you manage to write the tests in your local repo fork and they work fine. If you manage and it has not been implemented till then, you can open a new one.

**Comment by riturajjain2000** [comment]
> OK then, thanks and let's close the PR until you manage to write the tests in your local repo fork and they work fine. If you manage and it has not been implemented till then, you can open a new one.

Ok sir

**Pull request closed without merging**
