### PR TITLE
PAINTROID-292 Smudge tool

### PR DESCRIPTION
**Pull request by AneiMakovec**
1. The smudge tool creates a bitmap of the size of the brush on handle down and stores the pixel information from the selected layer.
2. It then stores amortized points in handle move, such that the points lead in the direction of the move, but are layed out at a fixed distance (to ensure that the drawed smudge would not contain any glitching effects).
3. On handle up it creates a new SmudgePathCommand, which then draws the stored bitmap with varying amounts of transparency at each of the stored points location.

The command ensures that the smudge is considered a single operation and can be entirely undone and redone by the user.
The tool also implements the draw function, which is used to preview the drawing of the smudge while the user is dragging the finger on the screen.
There are two parameters that are available in the tool's option menu: the pressure and the drag. The first determines how long the smudge will be (bigger value -> longer smudge). The second one determines how much will the smudge be reduced in size through its path (bigger value -> smaller reduction in size).

I also implemented tests for both the smudge tool and the SmudgePathCommand.

https://jira.catrob.at/browse/PAINTROID-292

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by FromG — CHANGES_REQUESTED** [review]
Fix static analysis warnings on jenkins. 
Rest looks good.

**Review by FromG — CHANGES_REQUESTED** [review]
squash commits pls.

**Review by FromG — APPROVED** [review]
ok

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
