### PR TITLE
PAINTROID-431 deleting unused file log.java

### PR DESCRIPTION
**Pull request by akebu6**
Refactored the log test in test/java/android/util from Java to Kotlin. Then, later realised file was never in use from the original nor the new branch and hence deleted the file

Ticket: https://jira.catrob.at/browse/PAINTROID-431

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by FromG — CHANGES_REQUESTED** [review]
fix static warnings on jenkins please.

**Comment by akebu6** [comment]
Got it, will do

**Comment by akebu6** [comment]
Any idea how I can fix the static warnings? I noticed them but wasn't sure how to go about fixing them

**Comment by FromG** [comment]
start
first you click on the details


then you have this option where it shows how many static warnings you have


when you click on the static warnings you will get to the different errors which occured. 
by clicking on the errors you can then see which files are affected.


if you further click on the file. you can then go to the exact line in the code.



here you can exactly see the warning in the code.

in this example ExpressionBodySyntax you should write it like this:
 fun d(tag: String, msg: String): Int = 0
i think there is also a option for converting to expressionbodysyntax in android studio.

**Comment by akebu6** [comment]
all right, let me work on them

**Comment by akebu6** [comment]
@FromG  the changes requested have been worked on, tests pass locally and on Jerkins. The file was deleted as it had no usages in both the develop branch and the new branch

**Review by ThorstenBandel — APPROVED** [review]
Thanks!

**Review by juliajulie95 — APPROVED** [review]

**Pull request merged**
