### PR TITLE
PAINTROID-212: Adapt format to original image

### PR DESCRIPTION
**Pull request by harsh-hash**
- first changed the format option for the loaded image
- second changed the format option for the new image

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by harsh-hash** [comment]
@wslany sir , I created this pr rebasing with the develop branch. This pr is reviewed by @ThorstenBandel. Please let me know if you need any changes.

**Comment by harsh-hash** [comment]
@ThorstenBandel sir it [(PR)](https://github.com/Catrobat/Paintroid/pull/885) is already reviewed by you. due to some issues, I created a new PR with the same changes. if you can approve changes it would be ready to merge.

**Comment by ThorstenBandel** [comment]
The other PR you created for this Ticket is already merged :)

**Comment by harsh-hash** [comment]
@ThorstenBandel sir Yes it was merged into Paintroid:212 branch but due to more than one commit @wslany sir again opened it as a new [PR](https://github.com/Catrobat/Paintroid/pull/885) so the changes I have made are not merged into develop branch.

**Comment by harsh-hash** [comment]
@wslany sir, is this ticket still unsolved?

**Comment by ThorstenBandel** [comment]
It was already merged with PR 879 :)
image

**Comment by harsh-hash** [comment]
@wslany @ThorstenBandel sir I know it is merged but I can't see these changes in develop branch.
I think @wslany sir merged this into the new PAINTROID-212 branch not in develop and after this by mistake this branch gets deleted.
So the changes are also deleted.

**Comment by wslany** [comment]
You are right!

**Comment by harsh-hash** [comment]
@wslany sir, can you please check the required functionality is working?

**Comment by wslany** [comment]
Functionality is fine, but one thing I am not sure is why Thorsten's commit regarding CrowdIn is shown again. It is already in the develop branch, so it should not be shown on the changes page.

Could you please rebase? Maybe that will solve the file commit confusion. You can do it directly on github, by tapping here:
image

**Comment by harsh-hash** [comment]
> Functionality is fine, but one thing I am not sure is why Thorsten's commit regarding CrowdIn is shown again. It is already in the develop branch, so it should not be shown on the changes page.
> 
> Could you please rebase? Maybe that will solve the file commit confusion. You can do it directly on github, by tapping here:
> image

I did this but it is still showing.

**Comment by harsh-hash** [comment]
I don't know why this always happens with this PR. Whenever I try to push commit and squash, it always starts showing another commit.

**Comment by harsh-hash** [comment]
Should I make a new one with the same changes?

**Comment by wslany** [comment]
> Should I make a new one with the same changes?
Maybe that's best, and please base it on the current develop version. Sorry for the troubles...

**Comment by harsh-hash** [comment]
@wslany sir created new #906 .

**Comment by wslany** [comment]
Thanks you!

**Pull request closed without merging**
