### PR TITLE
Paintroid-229 The brush tools alignment in right to left languages such as arabic

### PR DESCRIPTION
**Pull request by Edward1919**
*I changed the alignment of brush tools in right to left languages to remain in the left left to right format, for better UI in RTL marginEnd added in pocketpaint stroke types. 
*The tests also added in espresso rtl and is passed

*Strange behavior of cursor in RTL devices in brush stroke and spray tool edit text has been fixed.
 Seems that this type of strange cursor blinking in RTL in certain versions of devices, only happens when edit text is wrapped with an Input layout. In this case our TextInputEditText is wrapped with TextInputLayout.
 
*The tests already exist and are passed.
P.S. This PR is created after PR #862 because it had some problems.
before 1
after 1

### CODE REVIEW

**Comment by Edward1919** [comment]
Dear Sir this is new PR which is made after the PR #862 which had some problems. I still get 9 commits instead of 1 and it seems other commits are not mine. I am confused can you review and let me know what is the problem. Thanks.
@wslany @ThorstenBandel

**Comment by ThorstenBandel** [comment]
You need to git rebase onto develop instead of merging it thats why you have the commits

**Comment by wslany** [comment]
Hi @Edward1919 could you please try to rebase? This could solve the issue and also can now easily be done via github:
image

**Comment by Edward1919** [comment]
Sure. I will fix this.

**Comment by wslany** [comment]
Thank you!

**Comment by Edward1919** [comment]
@wslany Hi dear. I rebased according to instructions you gave. Fetch upstream. If you can squash the commits from your side please do. And if anything else needed let me know.
P.S. Sorry for late reply I wasnt feeling well in the past days.

**Comment by wslany** [comment]
Thanks @Edward1919 !!

**Pull request merged**
