### PR TITLE
PAINTROID - 471 : Refactor test cases from Java to Kotlin

### PR DESCRIPTION
**Pull request by bakicelebi**
[PAINTROID-471](https://jira.catrob.at/browse/PAINTROID-471)
Fixed the following refactored testcases:
- ToolControllerTest
- AutoScrollTaskTest
- DrawingSurfaceListenerTest
- LayerPresenterTest
- MainActivityPresenterTest

Additionally PointFAnswer and PointFMatcher needed to be translated from Java to Kotlin.
Used anyThat, any, eq from mockito-kotlin instead of java-mockito because of translation issues.(Added mockito-kotlin dependencie in gradle file)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Lenkomotive — APPROVED** [review]
👍🏼 very good

**Comment by Aditya3815** [comment]
hello, everyone I want to contribute to this project. Can you tell some good-first issues?

**Comment by Aditya3815** [comment]
I also want to join the Gsoc program for this project.

**Comment by exland** [comment]
@Aditya3815 HI, nice that you are interested in the project. If you want to contribute we have a small [landing page](https://confluence.catrob.at/display/KNOWHOW/Catrobat+Know-How). Where the start and everything is documented  :)

**Review by exland — APPROVED** [review]
Nice Good kotlin

**Comment by Aditya3815** [comment]
> @Aditya3815 HI, nice that you are interested in the project. If you want to contribute we have a small [landing page](https://confluence.catrob.at/display/KNOWHOW/Catrobat+Know-How). Where the start and everything is documented :)

Hi, @exland I can't able to log in Catrobat. It is asking me for a username & password but I am interested to contribute.

**Comment by Aditya3815** [comment]
Hi, @exland <https://github.com/exland> I can't able to log in Catrobat. It
is asking me for a username & password but I am interested to contribute.
Any other alternative method is there to contribute?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/02/23,
19:54:26

**Comment by exland** [comment]
@Aditya3815 Hi, you can signup for jira, Then you will have access to all the issues, documentation, workflow and everything else you need to contribute

**Pull request closed without merging**
