### PR TITLE
Paintroid 194 - Check all tests for correct behaviour

### PR DESCRIPTION
**Pull request by Electronix1337**
Refactoring unclear tests and fixing as many flaky tests as possible. Wrote a replacement for testBoundingBoxAlgorithm called testBorders. https://jira.catrob.at/browse/PAINTROID-194

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Electronix1337** [comment]
When running Jenkins with the two pipette tests (testPipetteAfterUndo, testPipetteAfterRedo) process crashes. And following lines are generated in the logcat.txt:

`11-25 11:36:38.594  2804  2815 I art     : Background sticky concurrent mark sweep GC freed 1742(64KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 39MB/39MB, paused 6.880ms total 32.407ms`
`11-25 11:36:38.608  1637  2126 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@f73d2a3 attribute=null, token = android.os.BinderProxy@b335c96`
`11-25 11:36:39.844  2804  2804 I ViewInteraction: Performing 'single click' action on view with id: org.catrobat.paintroid.test:id/pocketpaint_drawing_surface_view`
`11-25 11:36:39.876  2804  2812 W System.err: java.lang.Error: Cleaner terminated abnormally`
`11-25 11:36:39.877  2804  2812 W System.err: 	at sun.misc.Cleaner$1.run(Cleaner.java:147)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at sun.misc.Cleaner$1.run(Cleaner.java:145)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at java.security.AccessController.doPrivileged(AccessController.java:41)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at sun.misc.Cleaner.clean(Cleaner.java:144)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at java.lang.ref.ReferenceQueue.enqueueLocked(ReferenceQueue.java:75)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at java.lang.ref.ReferenceQueue.enqueuePending(ReferenceQueue.java:243)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:160)`
`11-25 11:36:39.877  2804  2812 W System.err: 	at java.lang.Thread.run(Thread.java:761)`
`11-25 11:36:39.878  2804  2812 W System.err: Caused by: java.lang.RuntimeException: Attempted to free 98 native bytes with only 30 native bytes registered as allocated`
`11-25 11:36:39.878  2804  2812 W System.err: 	at dalvik.system.VMRuntime.registerNativeFree(Native Method)`
`11-25 11:36:39.879  2804  2812 W System.err: 	at libcore.util.NativeAllocationRegistry.registerNativeFree(NativeAllocationRegistry.java:223)`
`11-25 11:36:39.879  2804  2812 W System.err: 	at libcore.util.NativeAllocationRegistry.-wrap0(NativeAllocationRegistry.java)`
`11-25 11:36:39.879  2804  2812 W System.err: 	at libcore.util.NativeAllocationRegistry$CleanerThunk.run(NativeAllocationRegistry.java:196)`
`11-25 11:36:39.879  2804  2812 W System.err: 	at sun.misc.Cleaner.clean(Cleaner.java:142)`
`11-25 11:36:39.879  2804  2812 W System.err: 	... 4 more`
`11-25 11:36:39.885  2804  2812 I art     : System.exit called, status: 1`

It seems like the GC tries to free the allocated memory but it tries to free more bytes than allocated. This always occurs either after singleclick on drawingsurface or after single click on undo button. Googled for the problem for several hours but no approach worked for us.

**Review by FromG — APPROVED** [review]
lgtm.

**Comment by StanglTobias** [comment]
Can we rewrite/fix/remove the failing testcase. Would be nice if every test passes after this ticket :)

**Comment by Electronix1337** [comment]
> Can we rewrite/fix/remove the failing testcase. Would be nice if every test passes after this ticket :)

Yeah i thought so too and after all tests ran through another random test started failing from time to time. I suspect that something with Jenkins or our test environment doesn't work 100%. The other day i saw a failing Jenkins build which passed all tests but the error still occured [(https://jenkins.catrob.at/job/Paintroid/job/PR-794/77/artifact/logcat.txt)](url) at the end of the document you can see the error log. As stated above it seems like the garbage collector tries to free more memory than allocated and after hours of research I could not find any solution to this problem. There are also some tests which fail on Jenkins every time but they're not testing anything special, like the undo/redo tests in the pipette tests. I talked with @wslany about this and he suggested to keep the tests and "@ignore" them rather than deleting them. We could try to remove the remaining ones separately and see if we can achieve a state where all tests constantly succeed? Otherwise I don't know a good way to fix this.

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
