### PR TITLE
PAINTROID-505 Fixed MenuFileActivityIntegrationTests

### PR DESCRIPTION
**Pull request by Rd4dev**
### Cause
The MediaStore content provider failed to retrieve the latest file name in the android API 28. Which caused the "ComparisonFailure" exception.

### Fix
Fixed it by replicating from testSameFileNameAfterOverwritePng where the URI is directly extracted from the savedPictureUri and File class and thereby eliminating the reliability on the content provider.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Rd4dev** [comment]
Update: This fix doesn't seem to work on the Jenkins build, but it did pass the test case locally. I will look into fixing it asap and if there are any suggestions, feel free to drop them :)

**Review by bakicelebi — CHANGES_REQUESTED** [review]
Hi @Rd4dev , test still fails on API 31 with ComparisonFailure and like you mentioned on jira, the catrobate-image file is still not flushed in @After teardDown() and a second test run results in failure.

**Comment by Rd4dev** [comment]
Hi @bakicelebi  , 
Thank you for reviewing the code. It appears that the file operations differ depending on the API version. Therefore, for API level Q and above, I created a 'File' object and added it to the 'deletionFileList', as these versions use isolated storage space. For API versions prior to Q, I passed the 'Uri' to the 'deletionFileList'. I tested the code locally on three different machines with API levels 28, 30, and 31. I hope this solution resolves the issue.

**Review by bakicelebi — APPROVED** [review]
Thank you! :+1:

**Review by ThorstenBandel — APPROVED** [review]

**Comment by Rd4dev** [comment]
Thanks @ThorstenBandel @bakicelebi

**Pull request merged**
