### PR TITLE
PAINTROID-12: Refactor public static tool state

### PR DESCRIPTION
**Pull request by ThomasSchwengler**
* Remove calls to static variables in tools
* Add `Workspace` class as wrapper for frequently used tool functions
* Add `ToolPaint` class to hold the currently used paint objects for tools
* Refactor tests to not use variables from `PaintroidApplication`
* Clean up `PaintroidApplication`
  * Remove `commandManager`
  * Remove `drawingSurface`
  * Remove `perspective`
  * Remove `layerModel`
* Refactor `PaintroidApplicationFragment`
  * Remove and don't persist `drawingSurface` anymore
  * Add and persist `toolPaint`
* Refactor tests to work without the removed public static variables

### CODE REVIEW

**Comment by ThomasSchwengler** [comment]
Rebased on current develop

**Comment by mrmattmueller** [comment]
Stamp not working...

**Comment by ThomasSchwengler** [comment]
Rebased

**Comment by ThomasSchwengler** [comment]
Rebased once again

**Pull request merged**
