### PR TITLE
PAINTROID-65: Color picker as fullscreen

### PR DESCRIPTION
**Pull request by ThomasSchwengler**
* Use color picker as fragment
* Add an optional action bar into colorpicker (workaround for our current main activity layout)
* Ensure that the color picker can still be used as a dialog
* Add a pleasing transition animation
* Change top bar size to default android action bar size

### CODE REVIEW

**Comment by mrmattmueller** [comment]
Please resolve conflicts

**Comment by Hiebl** [comment]
LGTM

**Comment by mrmattmueller** [comment]
I'm sorry :o

**Comment by geolas94** [comment]
after updating the branch to develop several tests fail, but the added feature works on manual testing

**Comment by geolas94** [comment]
rebuilding on jenkins passes all tests

**Pull request merged**
