### PR TITLE
PAINTROID-650 Zoom window shows wrong background

### PR DESCRIPTION
**Pull request by Lenkomotive**
[PAINTROID-650](https://jira.catrob.at/browse/PAINTROID-650)

Adapted the tool-compatibilities for zoomwindow usage.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by JulianJautz — CHANGES_REQUESTED** [review]
Watercolor, Spray and Brush were set to COMPATIBLE_NEW to fix the alpha-value-issue from https://jira.catrob.at/browse/PAINTROID-607.
With these changes the alpha value is not working again.

**Comment by bakicelebi** [comment]
> Watercolor, Spray and Brush were set to COMPATIBLE_NEW to fix the alpha-value-issue from https://jira.catrob.at/browse/PAINTROID-607. With these changes the alpha value is not working again.
> 
> I think it should work if you leave Watercolor, Spray and Brush as COMPATIBLE_NEW, but add all of them to the if in line 206.

**Comment by bakicelebi** [comment]
The transparency issue has been always here since [PAINTROID-433](https://github.com/Catrobat/Paintroid/pull/1131). I checked out and built the PR and it looks like every tool that is not COMPATIBLE_ALL has transparency issues. Additionally I have found a new related bug where Smudge tool ignores the transparency values of the pixel where the smudging happens. I suggest setting every tool that the zoom window supports to COMPATIBLE_NEW except eraser (surfaceViewCanvas.setBitmap(bitmapOfDrawingBoard) needs to be called to erase without artifacts). Afterwards the bitmaps of zoom window and background layer needs  to be merged. A simple checkIfToolCompatibleWithZoomWindow in line 206 in DefaultZoomWindowController should do it. This should fix all the bugs mentioned above.

**Review by bakicelebi — APPROVED** [review]
:+1: Looks good! @JulianJautz can you also take a look :)

**Comment by JulianJautz** [comment]
@bakicelebi @Lenkomotive
I tested it again and tried to use two layers. It seems like it does not work when more than one layer are used. E.g. when drawing on the second layer the background of the first layer is not shown in the zoom window...

**Comment by Lenkomotive** [comment]
> @bakicelebi @Lenkomotive I tested it again and tried to use two layers. It seems like it does not work when more than one layer are used. E.g. when drawing on the second layer the background of the first layer is not shown in the zoom window...
> 
> Alpha value issue looks good though!

The current implementation of the zoom window only supports the background of one layer. This has nothing to do with the bug in this ticket and should probably be addressed in another ticket. Lets discuss it in the next standup how we could resolve this issue. Thanks for checking! :)

**Comment by JulianJautz** [comment]
> > @bakicelebi @Lenkomotive I tested it again and tried to use two layers. It seems like it does not work when more than one layer are used. E.g. when drawing on the second layer the background of the first layer is not shown in the zoom window...
> > Alpha value issue looks good though!
> 
> The current implementation of the zoom window only supports the background of one layer. This has nothing to do with the bug in this ticket and should probably be addressed in another ticket. Lets discuss it in the next standup how we could resolve this issue. Thanks for checking! :)

Okay, then this fix for one layer is fine by me. :)

**Review by JulianJautz — APPROVED** [review]

**Pull request merged**
