### PR TITLE
PAINTROID-126: Drawingsurface with pipette in color picker for Catroid

### PR DESCRIPTION
**Pull request by ndrnour**
* using MaterialComponents style
* fix UI colors caused by changing the style 
* add kotlin dependencies for ColorPicker library
* new strings are annotated with `tools:ignore="MissingTranslation` please remove it once translations are available, otherwise Jenkins won't build the project

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by geolas94 — APPROVED** [review]
lgtm, test fails should be from jenkins only

**Review by ThorstenBandel — CHANGES_REQUESTED** [review]
The Color for the Pipette button should be the same as the "Done" button in the texttool
The dialog buttons "Cancel" and "Apply" should be in the same color as other Popups (e.g. the "Done" button in the overflow menu "About" section

**Comment by ndrnour** [comment]
@ThorstenBandel fixed

**Review by ThorstenBandel — APPROVED** [review]
Looks good to me. 
Only One thing: @wslany We should be able to keep the "tools:ignore="MissingTranslation"> " out (in the strings.xml, because our crowdin should now automatically translate all of that or?

**Comment by StanglTobias** [comment]
Alltough I see why it is needed for catroid that the pipette tool is used in a new activity I think we should overthink if we also should use this approach in the Paintroid Standalone. The colorpicker is very crowded, especially in the landscape mode we have got even less place, furthermore as always said we should adapt to the biggest players and i don't see e.g. Microsoft Paint or any other simple drawing tool opening a new screen for a simple pipette tool

**Comment by wslany** [comment]
> Alltough I see why it is needed for catroid that the pipette tool is used in a new activity I think we should overthink if we also should use this approach in the Paintroid Standalone. The colorpicker is very crowded, especially in the landscape mode we have got even less place, furthermore as always said we should adapt to the biggest players and i don't see e.g. Microsoft Paint or any other simple drawing tool opening a new screen for a simple pipette tool

@StanglTobias I just tried it on a phone in landscape mode, with paintroid in pop-up window mode, i.e., as small as possible, simulating a really tiny screen, and it still worked fine, even though the menu became a scrolling one. 
image

Maybe bring it up in one of the next meetings so we can address your concerns? Note that it is planned to eliminate the pipette from the normal tool menu, and keep it only in the color chooser in the future. This will make place for the new spray can tool in the tool menu raster. The pipette thus will also more intuitively be associated with colors, which is otherwise not ensured coming from a "pipette" symbol and name.

**Comment by wslany** [comment]
> Alltough I see why it is needed for catroid that the pipette tool is used in a new activity I think we should overthink if we also should use this approach in the Paintroid Standalone. The colorpicker is very crowded, especially in the landscape mode we have got even less place, furthermore as always said we should adapt to the biggest players and i don't see e.g. Microsoft Paint or any other simple drawing tool opening a new screen for a simple pipette tool

@StanglTobias Ahh, now I understood what you meant. Yes, you are right, I agree: 
- In Pocket Paint by itself, the pipette interface should remain simple, like when the pipette is used as a tool. No need for checkmark and arrow back in the top bar. The normal tools etc can be still shown at the bottom.
- Instead, the separate activity (with confirm checkmark in the top right, arrow back to the left in the top left) shall only be available when used within Catroid as a library. Actually, even there we might be able to avoid it. OK, we'll think it through once more. 

Thanks for pointing this out!

**Comment by wslany** [comment]
> * In Pocket Paint by itself, the pipette interface should remain simple, like when the pipette is used as a tool. No need for checkmark and arrow back in the top bar. The normal tools etc can be still shown at the bottom.

I just discussed it with @ThorstenBandel and we agreed that even in paintroid, the pipette should nevertheless be a separate activity, with the checkmark, because otherwise, once the pipette is not a separate tool by itself anymore, there can be a strange situation with a (different) tool like the brush at the bottom selected as the current tool, and then it would otherwise be unclear how to return to that tool once the user is using the pipette (you want to be able to correct the color, so the pipette mode should not finish with the first tap). So, the checkmark after all seems to be necessary, even for the stand alone version.

**Comment by wslany** [comment]
> Only One thing: @wslany We should be able to keep the "tools:ignore="MissingTranslation"> " out (in the strings.xml, because our crowdin should now automatically translate all of that or?

@ndrnour do we need this here? It _should_ be translated on CrowdIn, no?

**Review by wslany — CHANGES_REQUESTED** [review]
I just tried again, this time on my phone, and I found that the zoom level cannot be set as deep as in the normal paintroid drawing mode. It should be as deep as there, so to allow to select single pixels, like in the normal maximum paintroid zoom mode. 

Also, when the image is already zoomed and panned, and the pipette is chosen, currently the image is resized first, i.e., the zoom level and selected area are "forgotten". This should not be the case. The same area and zoom factor should be chosen like before tapping on the pipette button.

Also, after accepting the color chosen  with the pipette, the zoom factor and selected area and placement from before entering the color chooser are forgotten. This should not be the case. The zoom factor, the area, and the placement should still be there.

And also, in the normal pipette tool mode, it is possible to slide one finger, and see the color change at the same time. In the new mode, this feature is lost, and one has to single tap to select a color. Please also change this to make sliding possible again. In reverse, it is sufficient to pan using two fingers only, like in the normal paintroid.

**Review by wslany — CHANGES_REQUESTED** [review]
When zooming in, the black border around the image should be pushed out of the visible screen, just like in the normal view with other tools.

Transparent areas shall be shown in the gray/white rectangle mode, just like in the normal view with other tools, and change in size depending of the zoom level.

**Comment by wslany** [comment]
Is the lint warning on https://jenkins.catrob.at/job/Paintroid/job/PR-784/35/analysis/ something related to this PR, or unrelated and should be fixed independently?

**Comment by wslany** [comment]
Also, I tried to build with Catroid in build 37 on https://jenkins.catrob.at/job/Paintroid/job/PR-784/ but the Catroid build failed, see https://jenkins.catrob.at/job/Paintroid/job/PR-784/37/execution/node/44/log/ :
```
05:38:19  > Task :catroid:createCatroidDebugCompatibleScreenManifests
05:38:19  > Task :catroid:copyAndroidNatives
05:38:19  
05:38:19  > Task :catroid:processCatroidDebugManifest FAILED
05:38:19  /home/catroid/jenkins_slave/workspace/Paintroid_PR-784/Catroid/catroid/src/debug/AndroidManifest.xml:88:9-43 Error:
05:38:19  	Attribute application@name value=(org.catrobat.catroid.CatroidApplication) from AndroidManifest.xml:88:9-43
05:38:19  	is also present at [org.catrobat.paintroid:paintroid:2.5.2-LOCAL] AndroidManifest.xml:37:9-61 value=(androidx.multidex.MultiDexApplication).
05:38:19  	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:34:5-44:19 to override.
05:38:19  
05:38:19  See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
05:38:19  
05:38:20  
05:38:20  > Task :catroid:mergeCatroidDebugResources
05:38:20  
05:38:20  FAILURE: Build failed with an exception.
05:38:20  
05:38:20  * What went wrong:
05:38:20  Execution failed for task ':catroid:processCatroidDebugManifest'.
05:38:20  > Manifest merger failed : Attribute application@name value=(org.catrobat.catroid.CatroidApplication) from AndroidManifest.xml:88:9-43
05:38:20    	is also present at [org.catrobat.paintroid:paintroid:2.5.2-LOCAL] AndroidManifest.xml:37:9-61 value=(androidx.multidex.MultiDexApplication).
05:38:20    	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:34:5-44:19 to override.
05:38:20  
```

**Comment by ndrnour** [comment]
> > Only One thing: @wslany We should be able to keep the "tools:ignore="MissingTranslation"> " out (in the strings.xml, because our crowdin should now automatically translate all of that or?
> 
> @ndrnour do we need this here? It _should_ be translated on CrowdIn, no?

yeah, I add that just to get rid of the lint warnings, already removed.

**Comment by ndrnour** [comment]
> I just tried again, this time on my phone, and I found that the zoom level cannot be set as deep as in the normal paintroid drawing mode. It should be as deep as there, so to allow to select single pixels, like in the normal maximum paintroid zoom mode.

fixed
> 
> Also, when the image is already zoomed and panned, and the pipette is chosen, currently the image is resized first, i.e., the zoom level and selected area are "forgotten". This should not be the case. The same area and zoom factor should be chosen like before tapping on the pipette button.
> 
this is not part of my ticket, same case happens if you zoom and send Paintroid to background then open it again.
this can be fixed easily with LiveData and android architecture components instead of storing the stateBundle in onPause and restore it in onResume
> Also, after accepting the color chosen with the pipette, the zoom factor and selected area and placement from before entering the color chooser are forgotten. This should not be the case. The zoom factor, the area, and the placement should still be there.
> 
related to what I wrote up there
> And also, in the normal pipette tool mode, it is possible to slide one finger, and see the color change at the same time. In the new mode, this feature is lost, and one has to single tap to select a color. Please also change this to make sliding possible again. In reverse, it is sufficient to pan using two fingers only, like in the normal paintroid.

I'll fix that

**Comment by ndrnour** [comment]
> When zooming in, the black border around the image should be pushed out of the visible screen, just like in the normal view with other tools.
> 
puh! not sure this is doable with the CustomViews without getting strange zoom behavior, this works fine for Paintroid cause a SurfaceView is used, I can try to use a SurfaceView also for the Pipette but I can't guarantee the performance of the app anymore without using LiveData.
> Transparent areas shall be shown in the gray/white rectangle mode, just like in the normal view with other tools, and change in size depending of the zoom level.

I'll fix that

**Comment by ndrnour** [comment]
> Is the lint warning on https://jenkins.catrob.at/job/Paintroid/job/PR-784/35/analysis/ something related to this PR, or unrelated and should be fixed independently?

lint version should be upgraded, this can be done by upgrading the Gradle Plugin Version, which must be done in a separate ticket (upgrading Gradle plugin is always messy and could require many changes for other dependencies used in the project)

**Comment by ndrnour** [comment]
> Also, I tried to build with Catroid in build 37 on https://jenkins.catrob.at/job/Paintroid/job/PR-784/ but the Catroid build failed, see https://jenkins.catrob.at/job/Paintroid/job/PR-784/37/execution/node/44/log/ :
> 
> ```
> 05:38:19  > Task :catroid:createCatroidDebugCompatibleScreenManifests
> 05:38:19  > Task :catroid:copyAndroidNatives
> 05:38:19  
> 05:38:19  > Task :catroid:processCatroidDebugManifest FAILED
> 05:38:19  /home/catroid/jenkins_slave/workspace/Paintroid_PR-784/Catroid/catroid/src/debug/AndroidManifest.xml:88:9-43 Error:
> 05:38:19  	Attribute application@name value=(org.catrobat.catroid.CatroidApplication) from AndroidManifest.xml:88:9-43
> 05:38:19  	is also present at [org.catrobat.paintroid:paintroid:2.5.2-LOCAL] AndroidManifest.xml:37:9-61 value=(androidx.multidex.MultiDexApplication).
> 05:38:19  	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:34:5-44:19 to override.
> 05:38:19  
> 05:38:19  See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
> 05:38:19  
> 05:38:20  
> 05:38:20  > Task :catroid:mergeCatroidDebugResources
> 05:38:20  
> 05:38:20  FAILURE: Build failed with an exception.
> 05:38:20  
> 05:38:20  * What went wrong:
> 05:38:20  Execution failed for task ':catroid:processCatroidDebugManifest'.
> 05:38:20  > Manifest merger failed : Attribute application@name value=(org.catrobat.catroid.CatroidApplication) from AndroidManifest.xml:88:9-43
> 05:38:20    	is also present at [org.catrobat.paintroid:paintroid:2.5.2-LOCAL] AndroidManifest.xml:37:9-61 value=(androidx.multidex.MultiDexApplication).
> 05:38:20    	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:34:5-44:19 to override.
> 05:38:20  
> ```

interesting! I'll look into that

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
THanks!!

**Pull request merged**
