### PR TITLE
PAINTROID-389 color picker dialog color history

### PR DESCRIPTION
**Pull request by StanglTobias**
*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Nice! 
Please fix building with Catroid, which doesn't work anymore, see bottom of https://jenkins.catrob.at/job/Paintroid/job/PR-1118/17/execution/node/58/log/ 

Maybe a change on Catroid's side is required? Please remember that the color picker can be invoked as an independent module in the formula editor of Catroid, without calling the full Paintroid library as Catroid's image editor.
```
03:31:33  > Task :catroid:compileCatroidDebugJavaWithJavac
03:31:33  /home/catroid/jenkins_slave/workspace/Paintroid_PR-1118/Catroid/catroid/src/main/java/org/catrobat/catroid/content/strategy/ShowColorPickerFormulaEditorStrategy.java:101: error: method newInstance in class Companion cannot be applied to given types;
03:31:33  		ColorPickerDialog dialog = ColorPickerDialog.Companion.newInstance(currentColor, true,
03:31:33  		                                                      ^
03:31:33    required: int,boolean,boolean,ColorHistory
03:31:33    found: int,boolean,boolean
03:31:33    reason: actual and formal argument lists differ in length
03:31:33  /home/catroid/jenkins_slave/workspace/Paintroid_PR-1118/Catroid/catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorFragment.java:419: error: method newInstance in class Companion cannot be applied to given types;
03:31:33  		ColorPickerDialog dialog = ColorPickerDialog.Companion.newInstance(currentColor, true,
03:31:33  		                                                      ^
03:31:33    required: int,boolean,boolean,ColorHistory
03:31:33    found: int,boolean,boolean
03:31:33    reason: actual and formal argument lists differ in length
```

**Review by FromG — CHANGES_REQUESTED** [review]
Weird behaviour: Choose a color and close the colorpicker. Then open the color picker again and just close the color picker by clicking on the outside. 
This then adds the same color to the color history which was previously there. 
I dont mind it but it seems a bit odd. What are the opinions of @wslany and @ThorstenBandel on this? Should we implement a way that the same color cannot be saved into the color history?

-When you open a catrobat-image the selected color changes to the rightmost color in the color history. Once again im not a 100% sure if it should be the leftmost or the rightmost color.
However this is only a design question. 


Test fails on jenkins and locally, needs fixing:
tested with API28 pixel2
ColorDialogIntegrationTest.testSaveColorHistoryInCatrobatFile

androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131820652>[discard_button_text] value: Discard

**Review by FromG — APPROVED** [review]
overall it looks good. 
The only problem is the test ColorDialogIntegrationTest.testSaveColorHistoryInCatrobatFile.

However the reason why this test fails is because we have a bigger problem with the test system when we try to save files. In my opinion we should make an explicit ticket where we need to fix all the tests with file access. 
So i will approve this pr since everything works except this single test.

**Review by ThorstenBandel — APPROVED** [review]
LGTM

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
@FromG wrote:
> Weird behaviour: Choose a color and close the colorpicker. Then open the color picker again and just close the color picker by clicking on the outside. This then adds the same color to the color history which was previously there. I dont mind it but it seems a bit odd. What are the opinions of @wslany and @ThorstenBandel on this? Should we implement a way that the same color cannot be saved into the color history?

After discussion with @ThorstenBandel this will be fixed in a later ticket.

> -When you open a catrobat-image the selected color changes to the rightmost color in the color history. Once again im not a 100% sure if it should be the leftmost or the rightmost color. However this is only a design question.

According to @ThorstenBandel this was discussed and designed on purpose by the UX team in this way.

**Pull request merged**
