### PR TITLE
PAINTROID-409 Update Splashscreen to new Splashscreen API(android 12)

### PR DESCRIPTION
**Pull request by Aayush2111**
jira ticket: https://jira.catrob.at/browse/PAINTROID-409

Dark mode off: 
splashscreen1

Dark mode on:
splashscreen2

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aayush2111** [comment]
@ThorstenBandel 
could you review it please? thanks in advance! :)

**Comment by ThorstenBandel** [comment]
I moved the ticket to code review and someone will take a look at the Code then :) 
In the meantime: The unit tests seem to fail as it can be seen in:
https://jenkins.catrob.at/job/Paintroid/job/PR-1209/ 
Could you fix those please? If they are failing we can not merge the code :D

**Comment by Aayush2111** [comment]
> 

Sure, I will look into it!
is it failing due to my changes or was it failing previously too?

**Comment by ThorstenBandel** [comment]
The unit tests are due to the changes, you can compare it with the develop branch here https://jenkins.catrob.at/job/Paintroid/job/develop/

**Comment by Aayush2111** [comment]
> The unit tests are due to the changes, you can compare it with the develop branch here https://jenkins.catrob.at/job/Paintroid/job/develop/

Okay, I am looking into it! thanks!

**Comment by Aayush2111** [comment]
@ThorstenBandel Fixed! can you review it again?

**Comment by Aayush2111** [comment]
There seems to be some issue, I will make a new PR!

**Pull request closed without merging**
