### PR TITLE
PAINTROID-212: Adapt format to original image

### PR DESCRIPTION
**Pull request by harsh-hash**
Ticket Solve - https://jira.catrob.at/browse/PAINTROID-212
- first changed the format option for the loaded image
- second changed the format option for the new image

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by ThorstenBandel — CHANGES_REQUESTED** [review]
Hi, the code looks goot, i just found two edge cases that would also need to be done in this ticket: 
1) On save Copy the dialog should be the same as on save image
2) When opening save copy, canceling it and then opening save image again, it does not stay as the same file ending

It would be great if you can include these changes in your PR too :D

**Comment by harsh-hash** [comment]
@ThorstenBandel Sir added the requested changes. Please review.

**Comment by ThorstenBandel** [comment]
Thats works good now thanks. 2 More things: There is a test(testHandleActivityResultWhenLoadPictureThenLoadIntentPicture)  on Jenkins https://jenkins.catrob.at/job/Paintroid/job/PR-853/13/ that fails and the static analyis warnings would need to be fixed too before we can merge the PR (its only some small fixes: tabs instead of spaces, an unused import and each file needs to have an empty line at the end

If you have problems with the warnings dont hesitate to ask me

**Comment by harsh-hash** [comment]
Actually sir I tried to fix these warnings but it still has not fixed. Is there any option to add lint check locally so that I can assure before pushing it on GitHub.

**Comment by ThorstenBandel** [comment]
If you use android studio you can simply use the gradle button on the top right hand side then Paintroid -> Tasks -> other -> checkstyle 
and Paintroid -> Tasks -> verification-> lintDebug
These 2 should show all the warnings

**Comment by harsh-hash** [comment]
@ThorstenBandel  I made changes now all tests are passing. Please review it.

**Comment by ThorstenBandel** [comment]
One last small thing: the variable "imageFile " in Line 106 in MenuFileActivityIntegrationTest.java is not used ( only declarated in Line 111) 
If you could remove this variable, i think its ready to be merged

**Comment by harsh-hash** [comment]
I tried to solve this but after removing this again the bundle of warnings showed up(You can see this in last to last build)

**Comment by harsh-hash** [comment]
I tried to solve this but after removing this again the bundle of warnings showed up(You can see this in last to last build)

**Comment by ThorstenBandel** [comment]
I took a look at it: it seems like the Last PR didnt even run the other tests because that one failed. so you would need to remove the variable and then fix the other warnings(which are the ones i commented earlier)

**Comment by harsh-hash** [comment]
@ThorstenBandel sir I again pushed after removing the variable and I think it still the same problem. can you suggest me something and also 7 tests are failing?

**Comment by harsh-hash** [comment]
@ThorstenBandel Sir I think I had pushed and squashed some bad commits so if you allow me to make another PR with only the required changes then it may resolve these warnings and lint checks and can be easily reviewed.

**Comment by ThorstenBandel** [comment]
Yes sure you can of course close this one and create a new one if its easier for you :)
I will take a look at it when you created the new one then

**Comment by harsh-hash** [comment]
@ThorstenBandel Sir added a new [PR](https://github.com/Catrobat/Paintroid/pull/858)

**Comment by ThorstenBandel** [comment]
Closed. New PR is [https://github.com/Catrobat/Paintroid/pull/858]

**Pull request closed without merging**
