### PR TITLE
PAINTROID-212: Adapt format to original image

### PR DESCRIPTION
**Pull request by harsh-hash**
Ticket Solve - https://jira.catrob.at/browse/PAINTROID-212
- first changed the format option for the loaded image
- second changed the format option for the new image

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by ThorstenBandel** [comment]
This one Looks already better :)
The failed tests seem to be a similar error, i think if you manage to find the mistake in one it should fix all of them 

There are just 2 Checkstyle warnings you will have to fix (Import order = change the order of the imports (compare it to other test files)
And you have one import that is not used, you should be able to just delete this one
The last warning you can ignore that one is also on the develop

**Comment by harsh-hash** [comment]
@ThorstenBandel sir sorry for the delay. Can you please rebuild it since all test which is failing are passing locally?
Screenshot from 2021-04-17 14-52-27
Screenshot from 2021-04-17 14-57-19
Screenshot from 2021-04-17 14-58-22
Screenshot from 2021-04-17 15-03-33

**Comment by ThorstenBandel** [comment]
One last thing: can you move the import in MenuFileActivityIntegrationTest called
import static androidx.test.espresso.matcher.ViewMatchers.withSpinnerText;

To line 90? ( so in between .withID and .withText) so it is in the correct order then the PR should be ready to be merged :)

**Comment by ThorstenBandel** [comment]
it seems like the test testCheckCopyIsAlwaysDefaultOptions still seems to fail could you also take a look at that?

**Comment by wslany** [comment]
> it seems like the test testCheckCopyIsAlwaysDefaultOptions still seems to fail could you also take a look at that?

@ThorstenBandel that's already being fixed by #857 by @chbinder AFAIK, so no need to fix it here too. But a cross reviewing, also maybe with #870 from @CodeChamp-SS would be awesome.

**Comment by ThorstenBandel** [comment]
No this are the tests:
testSaveCopy
testShowOverwriteDialogAfterSavingAgain
The third test is  a new failing test :D

**Comment by harsh-hash** [comment]
@ThorstenBandel sir I think they are failing in Paintroid develop branch

**Comment by harsh-hash** [comment]
@ThorstenBandel sir, due to adding these [edge cases](https://github.com/Catrobat/Paintroid/pull/853#pullrequestreview-624939959) testCheckCopyIsAlwaysDefaultOptions is failing. because i have removed this `if (permissionCode == MainActivityConstants.PERMISSION_EXTERNAL_STORAGE_SAVE_COPY) {
			isStandard = true;
		}
` so due we need to also show spinner text as per the image extension when we click on save copy option.

**Comment by harsh-hash** [comment]
@ThorstenBandel @wslany sir, due to some issue in my local repo the two tests other than testCheckCopyIsAlwaysDefaultOptions() is failing so I have created a new [PR](https://github.com/Catrobat/Paintroid/pull/879). Please have a look at it. Thanks.

**Comment by wslany** [comment]
=> #879

**Pull request closed without merging**
